enum PlatformDefine {
    UNKNOWN = 'UNKNOWN',
    // Web Based
    MOBILE_BROWSER = 'MOBILE_BROWSER',
    DESKTOP_BROWSER = 'DESKTOP_BROWSER',
    // Native
    WIN32 = 'WIN32',
    ANDROID = 'ANDROID',
    IOS = 'IOS',
    MACOS = 'MACOS',
    OHOS = 'OHOS',
    OPENHARMONY = 'OPENHARMONY',
    // Minigame
    WECHAT_GAME = 'WECHAT_GAME',
    WECHAT_MINI_PROGRAM = 'WECHAT_MINI_PROGRAM',
    BAIDU_MINI_GAME = 'BAIDU_MINI_GAME',
    XIAOMI_QUICK_GAME = 'XIAOMI_QUICK_GAME',
    ALIPAY_MINI_GAME = 'ALIPAY_MINI_GAME',
    TAOBAO_CREATIVE_APP = 'TAOBAO_CREATIVE_APP',
    TAOBAO_MINI_GAME = 'TAOBAO_MINI_GAME',
    BYTEDANCE_MINI_GAME = 'BYTEDANCE_MINI_GAME',
    // Runtime Based
    OPPO_MINI_GAME = 'OPPO_MINI_GAME',
    VIVO_MINI_GAME = 'VIVO_MINI_GAME',
    HUAWEI_QUICK_GAME = 'HUAWEI_QUICK_GAME',
    LINKSURE_MINI_GAME = 'LINKSURE_MINI_GAME',
    QTT_MINI_GAME = 'QTT_MINI_GAME',
}

export default PlatformDefine;