export enum JSAPIMap {
    createBuffer,
    bindBuffer,
    bufferData,
    bufferSubData,
    bufferDataFromJs,
    createShader,
    shaderSource,
    compileShader,
    attachShader,
    detachShader,
    deleteShader,
    createProgram,
    useProgram,
    linkProgram,
    deleteProgram,
    disable,
    enable,
    cullFace,
    frontFace,
    polygonOffset,
    lineWidth,
    depthMask,
    depthFunc,
    stencilFuncSeparate,
    stencilOpSeparate,
    stencilMaskSeparate,
    blendColor,
    blendFuncSeparate,
    blendEquationSeparate,
    createTexture,
    bindTexture,
    deleteTexture,
    texParameteri,
    texImage2D,
    texSubImage2D,
    texSubImage2D_2,
    texSubImage2D_buffer,
    activeTexture,
    uniform1i,
    uniform2i,
    uniform3i,
    uniform4i,
    uniform1iv,
    uniform1f,
    uniform2f,
    uniform3f,
    uniform4f,
    uniform4fv,
    uniformMatrix4f,
    uniformMatrix2fv,
    uniformMatrix3fv,
    uniformMatrix4fv,
    enableVertexAttribArray,
    vertexAttribPointer,
    vertexAttribDivisor,
    drawElements,
    drawElementsInstancedANGLE,
    viewport,
    scissor,
    clear,
    clearColor,
    clearDepth,
    clearStencil,
    colorMask,
    createFramebuffer,
    bindFramebuffer,
    deleteFramebuffer,
    createRenderbuffer,
    deleteRenderbuffer,
    bindRenderbuffer,
    renderbufferStorage,
    framebufferRenderbuffer,
    framebufferTexture2D,
    beginWriteTempData,
    createVertexArrayOES,
    bindVertexArrayOES,
    deleteVertexArrayOES,
    createVertexArray, // WEBGL2.0
    bindVertexArray,   // WEBGL2.0
    deleteVertexArray, // WEBGL2.0
    drawElementsInstanced, // WEBGL2.0
    drawBuffers,
    createSampler,     // WEBGL2.0
    samplerParameteri, // WEBGL2.0
    bindSampler,       // WEBGL2.0
    deleteSampler,    //WEBGL2.0

    
    COUNT
}

export enum JSAPAGLEnum {
    ARRAY_BUFFER = 1,
    ELEMENT_ARRAY_BUFFER = 2,
    DYNAMIC_DRAW = 3,
    STATIC_DRAW = 4,
    VERTEX_SHADER = 5,
    FRAGMENT_SHADER = 6,
    CULL_FACE = 7,
    FRONT = 8,
    BACK = 9,
    CCW = 10,
    CW = 11,
    DEPTH_TEST = 12,
    STENCIL_TEST = 13,
    BLEND = 14,
    TEXTURE_2D = 15,
    REPEAT = 16,
    CLAMP_TO_EDGE = 17,
    LINEAR = 18,
    TEXTURE_WRAP_S = 19,
    TEXTURE_WRAP_T = 20,
    TEXTURE_MAG_FILTER = 21,
    TEXTURE_MIN_FILTER = 22,
    NEAREST = 23,
    MIRRORED_REPEAT = 24,
    NEAREST_MIPMAP_NEAREST = 25,
    NEAREST_MIPMAP_LINEAR = 26,
    LINEAR_MIPMAP_LINEAR = 27,

    UNSIGNED_BYTE = 200,
    UNSIGNED_SHORT = 201,
    UNSIGNED_INT = 202,
    BYTE = 203,
    SHORT = 204,
    FLOAT = 205,
    INT = 206,

    //Blend
    ZERO = 207,
    ONE = 208,
    SRC_COLOR = 209,
    DST_COLOR = 210,
    ONE_MINUS_SRC_COLOR = 211,
    ONE_MINUS_DST_COLOR = 212,
    SRC_ALPHA = 213,
    DST_ALPHA = 214,
    ONE_MINUS_DST_ALPHA = 215,
    CONSTANT_COLOR = 216,
    ONE_MINUS_CONSTANT_COLOR = 217,
    CONSTANT_ALPHA = 218,
    ONE_MINUS_CONSTANT_ALPHA = 219,
    ONE_MINUS_SRC_ALPHA = 220,
    SRC_ALPHA_SATURATE = 221,
    FUNC_ADD = 222,
    FUNC_SUBTRACT = 223,
    FUNC_REVERSE_SUBTRACT = 224,
    MIN = 225, //webgl2.0 。WebGL1.0需要扩展
    MAX = 226, //webgl2.0 WebGL1.0需要扩展

    DEPTH_BUFFER_BIT = 0x00000100, //256 
    STENCIL_BUFFER_BIT = 0x00000400, //1024
    COLOR_BUFFER_BIT = 0x00004000, //16384

    FRAMEBUFFER = 300,
    RENDERBUFFER = 301,
    COLOR_ATTACHMENT0 = 302,
    COLOR_ATTACHMENT1 = 303,
    COLOR_ATTACHMENT2 = 304,
    COLOR_ATTACHMENT3 = 305,
    COLOR_ATTACHMENT4 = 306,
    COLOR_ATTACHMENT5 = 307,
    COLOR_ATTACHMENT6 = 308,
    COLOR_ATTACHMENT7 = 309,
    DEPTH_STENCIL_ATTACHMENT = 340,
    DEPTH_ATTACHMENT = 341,
}
